name: Release livechart

on:
  push:
    branches:
      - main
    paths:
      - livechart/release.version

jobs:
  livechart:
    uses: ./.github/workflows/reusable-release.yml
    with:
      module_name: livechart
    secrets: inherit