name: Release notify

on:
  push:
    branches:
      - main
    paths:
      - notify/release.version

jobs:
  notify:
    uses: ./.github/workflows/reusable-release.yml
    with:
      module_name: notify
    secrets: inherit